noinst_LIBRARIES = libEnthalpyFDhighPr.a
libEnthalpyFDhighPr_a_SOURCES = enthalpyfdhighpr.h                 \
                                enthalpyfdhighpr_convection.cpp    \
                                enthalpyfdhighpr_new_time_step.cpp \
                                enthalpyfdhighpr_setflag.cpp

INCLUDE = -I@top_srcdir@/
