 #pragma once
#include "ThirdPartyHeadersBegin.h"
#include <map>
#include <vector>
#include <boost/unordered_set.hpp>
#include "ThirdPartyHeadersEnd.h"
#include "SZLFEPartitionedZoneHeaderWriter.h"
#include "ZoneWriterAbstract.h"
#include "PartitionTecUtilDecorator.h"
namespace tecplot { namespace ___3931 { class ___1348; class ___1350; class ___2722; class NodeToElemMap; class ZoneInfoCache; class ItemSetIterator; class SZLFEPartitionedZoneWriter : public ___4707 { public: SZLFEPartitionedZoneWriter( ItemSetIterator&              varIter, ___4634                   zone, ___4634                   ___341, std::vector<___372> const& ___4562, ___372                     ___4497, ___37&                   ___36, ZoneInfoCache&                zoneInfoCache); virtual ~SZLFEPartitionedZoneWriter(); protected: struct NeighborCellSubzoneInfo { std::vector<___2716> m_nodes; std::vector<___2716> m_neighborNodes; std::vector<boost::unordered_set<___2088::SubzoneOffset_t> > m_cellSubzones; std::vector<std::vector<___2477> > m_varMinMaxes; }; typedef std::map<___2088::___2978, NeighborCellSubzoneInfo> NeighborCellSubzoneInfoMap; void gatherNeighborCellSubzoneInfo(NeighborCellSubzoneInfoMap& neighborCellSubzoneInfoMap, ___2088::___2978 ___2975, ___4350 ___2841, ___2722& ___2721, std::vector<___1350> const& fieldDatas, ___1348 const& zoneInfo); virtual uint64_t zoneConnectivityFileSize(bool ___2000); virtual uint64_t zoneDataFileSize(bool ___2000); virtual uint64_t zoneHeaderFileSize(bool ___2000); virtual ___372 writeZoneConnectivity(FileWriterInterface& szpltFile); virtual ___372 writeZoneData(FileWriterInterface& szpltFile); virtual ___372 writeZoneHeader(FileWriterInterface& szpltFile); SZLFEPartitionedZoneHeaderWriter m_headerWriter; ZoneInfoCache& ___2678; PartitionTecUtilDecorator m_partitionTecUtil; ___2238<int32_t> m_partitionFileNums; UInt64Array m_partitionHeaderFilePositions; UInt32Array m_partitionNumCells; UInt32Array m_partitionNumNodes; VarZoneMinMaxArray m_varPartitionMinMaxes; std::map<___4634, boost::shared_ptr<___4707> > m_partitionWriters; private: void exchangeGhostInfo(std::vector<boost::shared_ptr<___1348> >& partitionInfos); void createPartitionWriters(); }; }}
