      INTEGER*4 FUNCTION tecini110

      INTEGER*4 FUNCTION teczne110

      INTEGER*4 FUNCTION tecdat110

      INTEGER*4 FUNCTION tecnod110

      INTEGER*4 FUNCTION tecend110

      INTEGER*4 FUNCTION teclab110

      INTEGER*4 FUNCTION tecusr110

      INTEGER*4 FUNCTION tecgeo110

      INTEGER*4 FUNCTION tectxt110

      INTEGER*4 FUNCTION tecfil110
      
      INTEGER*4 FUNCTION tecauxstr110
      
      INTEGER*4 FUNCTION teczauxstr110
      
      INTEGER*4 FUNCTION tecface110

      INTEGER*4 FUNCTION tecini

      INTEGER*4 FUNCTION teczne

      INTEGER*4 FUNCTION tecdat

      INTEGER*4 FUNCTION tecnod

      INTEGER*4 FUNCTION tecend 

      INTEGER*4 FUNCTION teclab

      INTEGER*4 FUNCTION tecusr

      INTEGER*4 FUNCTION tecgeo

      INTEGER*4 FUNCTION tectxt

      INTEGER*4 FUNCTION tecfil
