#!/bin/sh

TEC360HOME="/datalth/programs/tec360_2009"


FCOMPILER=f77
#F90COMPILER=f90
F90COMPILER=ifort
FFLAGS=
CCOMPILER=c89
EXTRALIBS=


USEBACKC=`echo "\c" | wc -c`
if test $USEBACKC -eq 0 ; then
  EFLAG=
  BACKC="\c"
else
  EFLAG=-n
  BACKC=
fi

if test $# -ge 2 ; then
  Model=$1
  TECLIBDIR=..
  INCDIR=../tecsrc
  BuildWhat=$2
  shift 
  shift
else
  if test "$TEC360HOME" != "" ; then
    TEC110HOME="$TEC360HOME"
  fi
  if test "$TEC110HOME" = "" ; then
    # NOTE: we intentionally only mention the $TEC360HOME environment variable.
    echo "Must have TEC360HOME environment variable set"
    exit
  fi
  TECLIBDIR=$TEC110HOME/lib
  INCDIR=$TEC110HOME/include
fi

if test $# -eq 0 ; then 
  echo 'Choose the model to build:'
  echo "ibmx64.51"
  echo "macx.103"
  echo "macix.104"
  echo "macix64.104"
  echo "linuxg23i64.24"
  echo "linuxg23.24"
  echo "linuxi64.24"
  echo "linux64.24"
  echo "linux64.26"
  echo "linux.24"
  echo "sgix64.65"
  echo "sun464.57"
  echo "  ALL"

  echo $EFLAG "--> $BACKC"

  read Model
fi




case $Model in
  sgix64.65) CFLAGS="-DIRIS -64 -mips4"
             CCOMPILER=CC
             FFLAGS="-64 -mips4"
             ;;
  sgix.65)   CFLAGS="-DIRIS -n32 -mips4"
             CCOMPILER=CC
             FFLAGS="-n32 -mips4"
             ;;
  ibmx64*)   CFLAGS="-DIBMRS6000 -q64"
             CCOMPILER=xlC
             F90COMPILER=xlf90
             FFLAGS="-q64"
             ;;
  ibmx*)     CFLAGS="-DIBMRS6000"
             CCOMPILER=xlC
             F90COMPILER=xlf90
             FFLAGS=
             ;;
  hp7xx64*)  CFLAGS="-AA -DHP +DA2.0W +DD64 +DS2.0W"
             CCOMPILER=aCC
             FFLAGS="+DA2.0W +DD64 +DS2.0W"
             FCOMPILER=f90
             ;;
  hp7xx*)    CFLAGS="-AA -DHP +DAportable"
             CCOMPILER=aCC
             FFLAGS="+DAportable"
             FCOMPILER=f90
             ;;
  sun464*)   CFLAGS="-DSUN -xarch=v9"
             FFLAGS="-xarch=v9"
             ;;
  sun4*)     CFLAGS="-DSUN"
             CCOMPILER=CC
             ;;
  linux*)    CCOMPILER=gcc
             CFLAGS="-DLINUX"
             EXTRALIBS=-lstdc++
             ;;
  mac*64*)   CCOMPILER=gcc
             CFLAGS="-m64 -DDARWIN"
             EXTRALIBS=-lstdc++
             ;;
  mac*)      CFLAGS="-DDARWIN"
             CCOMPILER=CC
             FFLAGS=
             EXTRALIBS=-lstdc++
             ;;
  *) echo "Invalid platform: $Model"
     exit;;
esac

case $Model in
  *64.*) TECLIBNAME=tecio64.a;;
      *) TECLIBNAME=tecio.a;;
esac


TECLIB=$TECLIBDIR/$TECLIBNAME


if test $# -eq 0 ; then
  echo "Choose test to build"
  echo " 1.  Simple C example"
  echo " 2.  Simple FORTRAN example"
  echo " 3.  Simple FORTRAN-90 example"
  echo " 4.  Complex C example"
  echo " 5.  Complex FORTRAN example"
  echo " 6.  Complex FORTRAN-90 example"
  echo " "

  read BuildWhat
fi


case $BuildWhat in
  1) $CCOMPILER -I.. -I$INCDIR $CFLAGS $* simtest.c $TECLIB -lm $EXTRALIBS -o simtest;;
  2) $FCOMPILER $FFLAGS $*    simtest.f $TECLIB -lm $EXTRALIBS -o simtest;;
  3) $F90COMPILER $FFLAGS $*    simtest.f90 $TECLIB -lm $EXTRALIBS -o simtest;;
  4) $CCOMPILER -I.. -I$INCDIR $CFLAGS comtest.c $TECLIB -lm $EXTRALIBS -o comtest;;
  5) $FCOMPILER $FFLAGS $*    comtest.f $* $TECLIB -lm $EXTRALIBS -o comtest;;
  6) $F90COMPILER $FFLAGS $*    comtest.f90 $* $TECLIB -lm $EXTRALIBS -o comtest;;
esac
