#!/bin/bash

#----------------------------------#
# this is coppied from Makefile.am #
#----------------------------------#
libs="Equation/Staggered/Momentum/libMomentum.a          \
      Solver/libSolver.a                                 \
      Equation/Centered/Enthalpy/libEnthalpy.a           \
      Equation/Centered/Concentration/libConcentration.a \
      Equation/Centered/Pressure/libPressure.a           \
      Equation/Centered/LevelSet/libLevelSet.a           \
      Equation/Centered/libCentered.a                    \
      Monitor/Rack/libRack.a                             \
      Monitor/Location/libLocation.a                     \
      Grid/libGrid.a                                     \
      Domain/libDomain.a                                 \
      Plot/libPlot.a                                     \
      Plot/GMV/libPlotGMV.a                              \
      Plot/VTK/libPlotVTK.a                              \
      Plot/TEC/libPlotTEC.a                              \
      Board/libBoard.a                                   \
      Body/libBody.a                                     \
      Field/Vector/libVector.a                           \
      Field/Scalar/libScalar.a                           \
      Timer/libTimer.a                                   \
      Formula/libFormula.a                               \
      Global/libGlobal.a                                 \
      Boundary/libBoundary.a                             \
      RandomFlow/libRandomFlow.a                         \
      Ravioli/libRavioli.a                               \
      Parallel/Out/libOut.a                              \
      Parallel/libParallel.a"

rm -f *.o

#----------------------------------#
# browse through all the libraries #
#----------------------------------#
for ilib in $libs; do

  echo $ilib
  
  # extract files from it
  ar x $ilib

  # add them to libBoil.a
  ar cru libBoil.a *.o

  # remove object files
  rm -f *.o

done
