#!/bin/bash

if [ $# -lt 7 ]; then
  echo "Usage: "
  echo $0 "<connect command> <base_name> <extension> <number of processors> <first_step> <last_step> <stride>"
else
  COMM=$1
  BASE=$2
  EXTN=$3
  NPRO=$4
  INIT=$5
  LAST=$6
  STEP=$7

  COUNTER=$INIT
  while [  $COUNTER -le $LAST ]; do
    echo Time: $COUNTER

    COMMAND=$COMM" "$BASE" "$EXTN" "$NPRO" "$COUNTER
    $COMMAND

    let COUNTER=COUNTER+$STEP

  done
fi
